const db = require('../config/database');
require('dotenv').config();
const bcrypt = require('bcryptjs');

const migrate = async () => {
  console.log('🔄 Running database migrations...\n');

  // Detect if using SQLite
  const isSQLite = process.env.DB_MODE === 'sqlite' || process.env.DB_HOST === 'mysql9.serv00.com';

  const sqliteQueries = [
    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password TEXT NOT NULL,
      phone TEXT DEFAULT NULL,
      role TEXT NOT NULL DEFAULT 'student',
      avatar TEXT DEFAULT NULL,
      hostel TEXT DEFAULT NULL,
      room_number TEXT DEFAULT NULL,
      is_verified INTEGER DEFAULT 0,
      is_suspended INTEGER DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS otp_codes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT NOT NULL,
      code TEXT NOT NULL,
      purpose TEXT NOT NULL DEFAULT 'register',
      expires_at TEXT NOT NULL,
      is_used INTEGER DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS shops (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      shop_name TEXT NOT NULL,
      description TEXT,
      location TEXT,
      is_open INTEGER DEFAULT 0,
      is_approved INTEGER DEFAULT 0,
      price_bw REAL DEFAULT 2.00,
      price_color REAL DEFAULT 5.00,
      price_binding REAL DEFAULT 30.00,
      rating REAL DEFAULT 0.00,
      total_orders INTEGER DEFAULT 0,
      wallet_balance REAL DEFAULT 0.00,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS orders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_hash TEXT NOT NULL UNIQUE,
      student_id INTEGER NOT NULL,
      shop_id INTEGER NOT NULL,
      status TEXT DEFAULT 'pending',
      delivery_type TEXT DEFAULT 'pickup',
      hostel_address TEXT DEFAULT NULL,
      print_type TEXT DEFAULT 'bw',
      layout TEXT DEFAULT 'single',
      copies INTEGER DEFAULT 1,
      binding INTEGER DEFAULT 0,
      total_pages INTEGER DEFAULT 0,
      total_price REAL DEFAULT 0.00,
      delivery_fee REAL DEFAULT 0.00,
      notes TEXT,
      agent_id INTEGER DEFAULT NULL,
      pickup_qr TEXT DEFAULT NULL,
      delivery_qr TEXT DEFAULT NULL,
      picked_up_at TEXT,
      delivered_at TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_files (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_id INTEGER NOT NULL,
      original_name TEXT NOT NULL,
      stored_name TEXT NOT NULL,
      file_path TEXT NOT NULL,
      file_size INTEGER DEFAULT 0,
      mime_type TEXT DEFAULT 'application/pdf',
      page_count INTEGER DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS deliveries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_id INTEGER NOT NULL,
      agent_id INTEGER NOT NULL,
      status TEXT DEFAULT 'assigned',
      pickup_verified INTEGER DEFAULT 0,
      dropoff_verified INTEGER DEFAULT 0,
      pickup_time TEXT,
      delivery_time TEXT,
      earnings REAL DEFAULT 0.00,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS transactions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      type TEXT NOT NULL,
      amount REAL NOT NULL,
      description TEXT,
      reference_id TEXT,
      balance_after REAL DEFAULT 0.00,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      title TEXT NOT NULL,
      message TEXT,
      type TEXT DEFAULT 'system',
      is_read INTEGER DEFAULT 0,
      metadata TEXT DEFAULT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS push_subscriptions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      endpoint TEXT NOT NULL,
      p256dh TEXT NOT NULL,
      auth TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      uuid TEXT NOT NULL UNIQUE,
      payment_reference TEXT NOT NULL UNIQUE,
      order_id INTEGER NOT NULL,
      student_id INTEGER NOT NULL,
      amount INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'INR',
      status TEXT NOT NULL,
      payment_method TEXT NOT NULL,
      gateway TEXT NOT NULL,
      idempotency_key TEXT NOT NULL UNIQUE,
      gateway_order_id TEXT DEFAULT NULL,
      gateway_payment_id TEXT DEFAULT NULL,
      error_code TEXT DEFAULT NULL,
      error_message TEXT DEFAULT NULL,
      provider_metadata TEXT DEFAULT NULL,
      verified_at TEXT DEFAULT NULL,
      failed_at TEXT DEFAULT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (student_id) REFERENCES users(id)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status)`,
    `CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id)`,
    `CREATE INDEX IF NOT EXISTS idx_payments_gateway_payment_id ON payments(gateway_payment_id)`,
    `CREATE TABLE IF NOT EXISTS payment_webhook_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      event_id TEXT NOT NULL UNIQUE,
      event_type TEXT NOT NULL,
      payment_uuid TEXT DEFAULT NULL,
      payment_reference TEXT DEFAULT NULL,
      gateway_order_id TEXT DEFAULT NULL,
      gateway_payment_id TEXT DEFAULT NULL,
      payload TEXT NOT NULL,
      headers TEXT NOT NULL,
      signature TEXT NOT NULL,
      payload_hash TEXT NOT NULL,
      processing_status TEXT NOT NULL,
      error_message TEXT DEFAULT NULL,
      processed_at TEXT DEFAULT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (payment_uuid) REFERENCES payments(uuid)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_webhook_events_payment_uuid ON payment_webhook_events(payment_uuid)`,
    `CREATE TABLE IF NOT EXISTS invoice_sequence (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      stub CHAR(1) NOT NULL UNIQUE
    )`,
    `CREATE TABLE IF NOT EXISTS order_number_sequence (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      stub CHAR(1) NOT NULL UNIQUE
    )`,
    `CREATE TABLE IF NOT EXISTS invoices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      uuid TEXT NOT NULL UNIQUE,
      invoice_number TEXT NOT NULL UNIQUE,
      student_id INTEGER NOT NULL,
      shop_id INTEGER NOT NULL,
      order_id INTEGER NOT NULL,
      order_hash TEXT NOT NULL,
      payment_uuid TEXT NOT NULL,
      payment_reference TEXT NOT NULL,
      gateway_payment_id TEXT NOT NULL,
      status TEXT NOT NULL,
      subtotal REAL NOT NULL,
      tax_amount REAL NOT NULL DEFAULT 0.00,
      total REAL NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id)
    )`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_uuid ON invoices(uuid)`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_number ON invoices(invoice_number)`,
    `CREATE TABLE IF NOT EXISTS print_jobs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_id INTEGER NOT NULL UNIQUE,
      shop_id INTEGER NOT NULL,
      student_id INTEGER NOT NULL,
      status TEXT NOT NULL,
      priority INTEGER DEFAULT 0,
      version INTEGER DEFAULT 1,
      last_status_changed_at TEXT DEFAULT NULL,
      accepted_at TEXT DEFAULT NULL,
      printing_started_at TEXT DEFAULT NULL,
      ready_at TEXT DEFAULT NULL,
      cancelled_at TEXT DEFAULT NULL,
      completed_at TEXT DEFAULT NULL,
      cancellation_reason_code TEXT DEFAULT NULL,
      cancellation_description TEXT DEFAULT NULL,
      estimated_completion_at TEXT DEFAULT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_print_jobs_status ON print_jobs(status)`,
    `CREATE TABLE IF NOT EXISTS print_job_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      print_job_id INTEGER NOT NULL,
      previous_status TEXT NOT NULL,
      new_status TEXT NOT NULL,
      actor_type TEXT NOT NULL,
      transition_name TEXT NOT NULL,
      changed_by_user_id INTEGER NOT NULL,
      reason_code TEXT DEFAULT NULL,
      reason_description TEXT DEFAULT NULL,
      correlation_id TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (print_job_id) REFERENCES print_jobs(id),
      FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_print_job_history_job_id ON print_job_history(print_job_id)`,
    `CREATE TABLE IF NOT EXISTS outbox_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      event_id TEXT NOT NULL UNIQUE,
      event_type TEXT NOT NULL,
      aggregate_type TEXT NOT NULL,
      aggregate_id TEXT NOT NULL,
      payload TEXT NOT NULL,
      status TEXT NOT NULL,
      retry_count INTEGER DEFAULT 0,
      error_log TEXT DEFAULT NULL,
      correlation_id TEXT NOT NULL,
      event_version INTEGER NOT NULL DEFAULT 1,
      occurred_at TEXT DEFAULT CURRENT_TIMESTAMP,
      worker_id TEXT DEFAULT NULL,
      processing_started_at TEXT DEFAULT NULL,
      processed_at TEXT DEFAULT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_outbox_events_status ON outbox_events(status)`,
    `CREATE TABLE IF NOT EXISTS fulfillments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_id INTEGER NOT NULL UNIQUE,
      print_job_id INTEGER NOT NULL UNIQUE,
      shop_id INTEGER NOT NULL,
      student_id INTEGER NOT NULL,
      status TEXT NOT NULL,
      mode TEXT NOT NULL,
      assigned_agent_id INTEGER DEFAULT NULL,
      otp_hash TEXT DEFAULT NULL,
      otp_expires_at TEXT DEFAULT NULL,
      otp_attempts INTEGER DEFAULT 0,
      delivery_attempts INTEGER DEFAULT 0,
      proof_of_delivery_reference TEXT DEFAULT NULL,
      failure_reason TEXT DEFAULT NULL,
      estimated_delivery_at TEXT DEFAULT NULL,
      actual_delivery_at TEXT DEFAULT NULL,
      otp_verified_at TEXT DEFAULT NULL,
      version INTEGER DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (print_job_id) REFERENCES print_jobs(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id),
      FOREIGN KEY (assigned_agent_id) REFERENCES users(id)
    )`,
    `CREATE TABLE IF NOT EXISTS fulfillment_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      fulfillment_id INTEGER NOT NULL,
      previous_status TEXT NOT NULL,
      new_status TEXT NOT NULL,
      transition_name TEXT NOT NULL,
      performed_by_type TEXT NOT NULL,
      performed_by_user_id INTEGER NOT NULL,
      failure_reason TEXT DEFAULT NULL,
      proof_of_delivery_reference TEXT DEFAULT NULL,
      metadata TEXT DEFAULT NULL,
      correlation_id TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (fulfillment_id) REFERENCES fulfillments(id),
      FOREIGN KEY (performed_by_user_id) REFERENCES users(id)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_fulfillments_status ON fulfillments(status)`,
    `CREATE INDEX IF NOT EXISTS idx_fulfillments_order_id ON fulfillments(order_id)`,
    `CREATE INDEX IF NOT EXISTS idx_fulfillments_print_job_id ON fulfillments(print_job_id)`,
    `CREATE INDEX IF NOT EXISTS idx_fulfillment_history_fulfillment_id ON fulfillment_history(fulfillment_id)`,
    `CREATE TABLE IF NOT EXISTS delivery_agent_availability (
      agent_id INTEGER PRIMARY KEY,
      status TEXT NOT NULL DEFAULT 'AVAILABLE',
      active_workload INTEGER DEFAULT 0,
      last_assigned_at TEXT DEFAULT NULL,
      last_idle_at TEXT DEFAULT NULL,
      version INTEGER DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (agent_id) REFERENCES users(id)
    )`,
    `CREATE TABLE IF NOT EXISTS delivery_assignments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      fulfillment_id INTEGER NOT NULL,
      order_id INTEGER NOT NULL,
      shop_id INTEGER NOT NULL,
      student_id INTEGER NOT NULL,
      agent_id INTEGER NOT NULL,
      status TEXT NOT NULL,
      correlation_id TEXT NOT NULL,
      version INTEGER DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (fulfillment_id) REFERENCES fulfillments(id),
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (agent_id) REFERENCES users(id)
    )`,
    `CREATE TABLE IF NOT EXISTS delivery_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      delivery_assignment_id INTEGER NOT NULL,
      previous_status TEXT NOT NULL,
      new_status TEXT NOT NULL,
      transition_name TEXT NOT NULL,
      performed_by_user_id INTEGER NOT NULL,
      performed_by_type TEXT NOT NULL,
      metadata TEXT DEFAULT NULL,
      correlation_id TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (delivery_assignment_id) REFERENCES delivery_assignments(id),
      FOREIGN KEY (performed_by_user_id) REFERENCES users(id)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_delivery_agent_availability_status ON delivery_agent_availability(status)`,
    `CREATE INDEX IF NOT EXISTS idx_delivery_assignments_status ON delivery_assignments(status)`,
    `CREATE INDEX IF NOT EXISTS idx_delivery_assignments_fulfillment_id ON delivery_assignments(fulfillment_id)`,
    `CREATE INDEX IF NOT EXISTS idx_delivery_assignments_agent_id ON delivery_assignments(agent_id)`,
    `CREATE INDEX IF NOT EXISTS idx_delivery_history_assignment_id ON delivery_history(delivery_assignment_id)`,

    // ─── Phase 7: Order Tracking & Lifecycle Projection (SQLite) ───────────
    `CREATE TABLE IF NOT EXISTS processed_events (
      event_id TEXT PRIMARY KEY,
      processed_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_lifecycle_projections (
      order_id INTEGER PRIMARY KEY,
      order_hash TEXT NOT NULL UNIQUE,
      student_id INTEGER NOT NULL,
      shop_id INTEGER NOT NULL,
      shop_name TEXT NOT NULL,
      delivery_type TEXT NOT NULL,
      hostel_address TEXT DEFAULT NULL,
      total_price REAL NOT NULL,
      current_state TEXT NOT NULL,
      payment_status TEXT NOT NULL,
      invoice_number TEXT DEFAULT NULL,
      print_job_id INTEGER DEFAULT NULL,
      print_status TEXT DEFAULT NULL,
      fulfillment_id INTEGER DEFAULT NULL,
      fulfillment_status TEXT DEFAULT NULL,
      assigned_agent_id INTEGER DEFAULT NULL,
      agent_name TEXT DEFAULT NULL,
      agent_phone TEXT DEFAULT NULL,
      last_processed_version INTEGER NOT NULL DEFAULT 0,
      last_processed_occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_proj_student ON order_lifecycle_projections(student_id)`,
    `CREATE INDEX IF NOT EXISTS idx_proj_shop ON order_lifecycle_projections(shop_id)`,
    `CREATE INDEX IF NOT EXISTS idx_proj_agent ON order_lifecycle_projections(assigned_agent_id)`,
    `CREATE TABLE IF NOT EXISTS order_lifecycle_timeline_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_id INTEGER NOT NULL,
      event_id TEXT NOT NULL,
      event_type TEXT NOT NULL,
      state TEXT NOT NULL,
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      occurred_at TEXT NOT NULL,
      actor_type TEXT NOT NULL,
      actor_id INTEGER DEFAULT NULL,
      metadata TEXT DEFAULT NULL,
      correlation_id TEXT NOT NULL,
      causation_id TEXT NOT NULL,
      FOREIGN KEY (order_id) REFERENCES order_lifecycle_projections(order_id) ON DELETE CASCADE,
      UNIQUE(order_id, event_id)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_timeline_occurred ON order_lifecycle_timeline_events(order_id, occurred_at)`,
    `CREATE INDEX IF NOT EXISTS idx_timeline_event_id ON order_lifecycle_timeline_events(event_id)`,
    `CREATE INDEX IF NOT EXISTS idx_timeline_correlation ON order_lifecycle_timeline_events(correlation_id)`,
    `CREATE TABLE IF NOT EXISTS dead_letter_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      event_id TEXT NOT NULL UNIQUE,
      aggregate_id TEXT NOT NULL,
      aggregate_type TEXT NOT NULL,
      event_type TEXT NOT NULL,
      payload TEXT NOT NULL,
      error_message TEXT NOT NULL,
      retry_count INTEGER NOT NULL,
      failed_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS scheduling_shops_capacity (
      shop_id INTEGER PRIMARY KEY,
      max_parallel_orders INTEGER NOT NULL DEFAULT 5,
      overload_wait_threshold_seconds INTEGER NOT NULL DEFAULT 7200,
      is_accepting_orders INTEGER NOT NULL DEFAULT 1,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS scheduling_printers (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shop_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      status TEXT NOT NULL,
      pages_per_minute INTEGER NOT NULL DEFAULT 20,
      duplex_supported INTEGER NOT NULL DEFAULT 1,
      color_supported INTEGER NOT NULL DEFAULT 1,
      supported_paper_sizes TEXT NOT NULL,
      maximum_paper_weight INTEGER NOT NULL DEFAULT 80,
      printable_media TEXT NOT NULL,
      warmup_time_seconds INTEGER NOT NULL DEFAULT 30,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (shop_id) REFERENCES scheduling_shops_capacity(shop_id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS scheduling_printer_maintenance (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      printer_id INTEGER NOT NULL,
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      reason TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (printer_id) REFERENCES scheduling_printers(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS scheduling_print_queue (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shop_id INTEGER NOT NULL,
      order_id INTEGER NOT NULL UNIQUE,
      printer_id INTEGER DEFAULT NULL,
      queue_position INTEGER NOT NULL DEFAULT 0,
      estimated_start_time TEXT NOT NULL,
      estimated_completion_time TEXT NOT NULL,
      pages_count INTEGER NOT NULL,
      duplex INTEGER NOT NULL DEFAULT 0,
      color INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (shop_id) REFERENCES scheduling_shops_capacity(shop_id) ON DELETE CASCADE,
      FOREIGN KEY (printer_id) REFERENCES scheduling_printers(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS scheduling_inventory (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shop_id INTEGER NOT NULL,
      type TEXT NOT NULL,
      variant TEXT NOT NULL,
      quantity REAL NOT NULL DEFAULT 0.0,
      unit TEXT NOT NULL,
      low_stock_threshold REAL NOT NULL DEFAULT 100.0,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(shop_id, type, variant),
      FOREIGN KEY (shop_id) REFERENCES scheduling_shops_capacity(shop_id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS scheduling_processed_events (
      event_id TEXT PRIMARY KEY,
      processed_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS scheduling_snapshots (
      shop_id INTEGER PRIMARY KEY,
      last_event_id TEXT NOT NULL,
      last_event_sequence INTEGER NOT NULL,
      state_data TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      type TEXT NOT NULL,
      priority TEXT NOT NULL,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      is_read INTEGER NOT NULL DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS notification_templates (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL UNIQUE,
      subject TEXT DEFAULT NULL,
      body_markdown TEXT NOT NULL,
      body_html TEXT NOT NULL,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS notification_preferences (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL UNIQUE,
      email_enabled INTEGER NOT NULL DEFAULT 1,
      in_app_enabled INTEGER NOT NULL DEFAULT 1,
      quiet_hours_start TEXT DEFAULT NULL,
      quiet_hours_end TEXT DEFAULT NULL,
      min_priority TEXT DEFAULT 'low',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS notification_delivery_attempts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      notification_id INTEGER NOT NULL,
      channel TEXT NOT NULL,
      status TEXT NOT NULL,
      error_message TEXT DEFAULT NULL,
      attempted_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS notification_batches (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shop_id INTEGER NOT NULL,
      recipient_count INTEGER NOT NULL,
      status TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS processed_notification_events (
      event_id TEXT PRIMARY KEY,
      processed_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS analytics_daily_metrics (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      date TEXT NOT NULL UNIQUE,
      total_orders INTEGER NOT NULL DEFAULT 0,
      total_revenue REAL NOT NULL DEFAULT 0.0,
      completed_orders INTEGER NOT NULL DEFAULT 0,
      cancelled_orders INTEGER NOT NULL DEFAULT 0,
      avg_completion_time_secs REAL NOT NULL DEFAULT 0.0,
      avg_delivery_time_secs REAL NOT NULL DEFAULT 0.0,
      low_stock_events INTEGER NOT NULL DEFAULT 0,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS analytics_shop_metrics (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shop_id INTEGER NOT NULL UNIQUE,
      total_orders INTEGER NOT NULL DEFAULT 0,
      completed_orders INTEGER NOT NULL DEFAULT 0,
      cancelled_orders INTEGER NOT NULL DEFAULT 0,
      total_revenue REAL NOT NULL DEFAULT 0.0,
      avg_completion_time_secs REAL NOT NULL DEFAULT 0.0,
      avg_delivery_time_secs REAL NOT NULL DEFAULT 0.0,
      printer_utilization_pct REAL NOT NULL DEFAULT 0.0,
      queue_utilization_pct REAL NOT NULL DEFAULT 0.0,
      low_stock_events INTEGER NOT NULL DEFAULT 0,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS analytics_user_metrics (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL UNIQUE,
      total_orders INTEGER NOT NULL DEFAULT 0,
      completed_orders INTEGER NOT NULL DEFAULT 0,
      cancelled_orders INTEGER NOT NULL DEFAULT 0,
      total_spend REAL NOT NULL DEFAULT 0.0,
      avg_order_value REAL NOT NULL DEFAULT 0.0,
      last_order_at TEXT DEFAULT NULL,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS analytics_order_facts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_id INTEGER NOT NULL UNIQUE,
      shop_id INTEGER NOT NULL,
      user_id INTEGER NOT NULL,
      date TEXT NOT NULL,
      revenue REAL NOT NULL DEFAULT 0.0,
      page_count INTEGER NOT NULL DEFAULT 0,
      is_color INTEGER NOT NULL DEFAULT 0,
      order_created_at TEXT NOT NULL,
      payment_confirmed_at TEXT DEFAULT NULL,
      print_started_at TEXT DEFAULT NULL,
      print_completed_at TEXT DEFAULT NULL,
      delivery_completed_at TEXT DEFAULT NULL,
      cancelled_at TEXT DEFAULT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS analytics_events_processed (
      event_id TEXT PRIMARY KEY,
      processed_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS analytics_snapshots (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      snapshot_date TEXT NOT NULL UNIQUE,
      total_orders INTEGER NOT NULL DEFAULT 0,
      total_revenue REAL NOT NULL DEFAULT 0.0,
      total_completed INTEGER NOT NULL DEFAULT 0,
      total_cancelled INTEGER NOT NULL DEFAULT 0,
      last_event_sequence INTEGER NOT NULL DEFAULT 0,
      state_data TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`
  ];

  const mysqlQueries = [
    `CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      phone VARCHAR(20) DEFAULT NULL,
      role ENUM('student','shop','agent','admin') NOT NULL DEFAULT 'student',
      avatar VARCHAR(500) DEFAULT NULL,
      hostel VARCHAR(100) DEFAULT NULL,
      room_number VARCHAR(20) DEFAULT NULL,
      is_verified TINYINT(1) DEFAULT 0,
      is_suspended TINYINT(1) DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS otp_codes (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL,
      code VARCHAR(6) NOT NULL,
      purpose ENUM('register','login','reset') NOT NULL DEFAULT 'register',
      expires_at TIMESTAMP NOT NULL,
      is_used TINYINT(1) DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_email_code (email, code)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS shops (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      shop_name VARCHAR(200) NOT NULL,
      description TEXT,
      location VARCHAR(300),
      is_open TINYINT(1) DEFAULT 0,
      is_approved TINYINT(1) DEFAULT 0,
      price_bw DECIMAL(10,2) DEFAULT 2.00,
      price_color DECIMAL(10,2) DEFAULT 5.00,
      price_binding DECIMAL(10,2) DEFAULT 30.00,
      rating DECIMAL(3,2) DEFAULT 0.00,
      total_orders INT DEFAULT 0,
      wallet_balance DECIMAL(12,2) DEFAULT 0.00,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS orders (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_hash VARCHAR(64) NOT NULL UNIQUE,
      student_id INT NOT NULL,
      shop_id INT NOT NULL,
      status ENUM('pending','confirmed','printing','ready','out_for_delivery','delivered','cancelled') DEFAULT 'pending',
      delivery_type ENUM('pickup','hostel') DEFAULT 'pickup',
      hostel_address VARCHAR(300) DEFAULT NULL,
      print_type ENUM('bw','color') DEFAULT 'bw',
      layout ENUM('single','double') DEFAULT 'single',
      copies INT DEFAULT 1,
      binding TINYINT(1) DEFAULT 0,
      total_pages INT DEFAULT 0,
      total_price DECIMAL(12,2) DEFAULT 0.00,
      delivery_fee DECIMAL(10,2) DEFAULT 0.00,
      notes TEXT,
      agent_id INT DEFAULT NULL,
      pickup_qr TEXT DEFAULT NULL,
      delivery_qr TEXT DEFAULT NULL,
      picked_up_at TIMESTAMP NULL,
      delivered_at TIMESTAMP NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id),
      INDEX idx_status (status),
      INDEX idx_student (student_id),
      INDEX idx_shop (shop_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS order_files (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_id INT NOT NULL,
      original_name VARCHAR(500) NOT NULL,
      stored_name VARCHAR(500) NOT NULL,
      file_path VARCHAR(1000) NOT NULL,
      file_size INT DEFAULT 0,
      mime_type VARCHAR(100) DEFAULT 'application/pdf',
      page_count INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS deliveries (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_id INT NOT NULL,
      agent_id INT NOT NULL,
      status ENUM('assigned','picked_up','in_transit','delivered','failed') DEFAULT 'assigned',
      pickup_verified TINYINT(1) DEFAULT 0,
      dropoff_verified TINYINT(1) DEFAULT 0,
      pickup_time TIMESTAMP NULL,
      delivery_time TIMESTAMP NULL,
      earnings DECIMAL(10,2) DEFAULT 0.00,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (agent_id) REFERENCES users(id),
      INDEX idx_agent (agent_id),
      INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS transactions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      type ENUM('credit','debit') NOT NULL,
      amount DECIMAL(12,2) NOT NULL,
      description VARCHAR(500),
      reference_id VARCHAR(100),
      balance_after DECIMAL(12,2) DEFAULT 0.00,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id),
      INDEX idx_user (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS notifications (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      title VARCHAR(200) NOT NULL,
      message TEXT,
      type ENUM('order','delivery','system','wallet') DEFAULT 'system',
      is_read TINYINT(1) DEFAULT 0,
      metadata JSON DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      INDEX idx_user_read (user_id, is_read)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS push_subscriptions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      endpoint TEXT NOT NULL,
      p256dh VARCHAR(500) NOT NULL,
      auth VARCHAR(500) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      INDEX idx_user (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS payments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      uuid VARCHAR(36) NOT NULL UNIQUE,
      payment_reference VARCHAR(50) NOT NULL UNIQUE,
      order_id INT NOT NULL,
      student_id INT NOT NULL,
      amount INT NOT NULL,
      currency VARCHAR(10) NOT NULL DEFAULT 'INR',
      status VARCHAR(50) NOT NULL,
      payment_method VARCHAR(50) NOT NULL,
      gateway VARCHAR(50) NOT NULL,
      idempotency_key VARCHAR(255) NOT NULL UNIQUE,
      gateway_order_id VARCHAR(255) DEFAULT NULL,
      gateway_payment_id VARCHAR(255) DEFAULT NULL,
      error_code VARCHAR(100) DEFAULT NULL,
      error_message VARCHAR(500) DEFAULT NULL,
      provider_metadata JSON DEFAULT NULL,
      verified_at TIMESTAMP NULL DEFAULT NULL,
      failed_at TIMESTAMP NULL DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      INDEX idx_payments_status (status),
      INDEX idx_payments_order_id (order_id),
      INDEX idx_payments_gateway_payment_id (gateway_payment_id),
      INDEX idx_payments_uuid (uuid),
      INDEX idx_payments_reference (payment_reference)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS payment_webhook_events (
      id INT AUTO_INCREMENT PRIMARY KEY,
      event_id VARCHAR(255) NOT NULL UNIQUE,
      event_type VARCHAR(100) NOT NULL,
      payment_uuid VARCHAR(36) DEFAULT NULL,
      payment_reference VARCHAR(50) DEFAULT NULL,
      gateway_order_id VARCHAR(255) DEFAULT NULL,
      gateway_payment_id VARCHAR(255) DEFAULT NULL,
      payload LONGTEXT NOT NULL,
      headers TEXT NOT NULL,
      signature VARCHAR(500) NOT NULL,
      payload_hash VARCHAR(64) NOT NULL,
      processing_status VARCHAR(50) NOT NULL,
      error_message TEXT DEFAULT NULL,
      processed_at TIMESTAMP NULL DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (payment_uuid) REFERENCES payments(uuid),
      INDEX idx_webhook_events_payment_uuid (payment_uuid),
      INDEX idx_webhook_events_event_id (event_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS invoice_sequence (
      id INT AUTO_INCREMENT PRIMARY KEY,
      stub CHAR(1) NOT NULL UNIQUE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS order_number_sequence (
      id INT AUTO_INCREMENT PRIMARY KEY,
      stub CHAR(1) NOT NULL UNIQUE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS invoices (
      id INT AUTO_INCREMENT PRIMARY KEY,
      uuid VARCHAR(36) NOT NULL UNIQUE,
      invoice_number VARCHAR(100) NOT NULL UNIQUE,
      student_id INT NOT NULL,
      shop_id INT NOT NULL,
      order_id INT NOT NULL,
      order_hash VARCHAR(64) NOT NULL,
      payment_uuid VARCHAR(36) NOT NULL,
      payment_reference VARCHAR(100) NOT NULL,
      gateway_payment_id VARCHAR(255) NOT NULL,
      status VARCHAR(50) NOT NULL,
      subtotal DECIMAL(12,2) NOT NULL,
      tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      total DECIMAL(12,2) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id),
      INDEX idx_invoices_order_id (order_id),
      INDEX idx_invoices_uuid (uuid),
      INDEX idx_invoices_number (invoice_number)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS print_jobs (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_id INT NOT NULL UNIQUE,
      shop_id INT NOT NULL,
      student_id INT NOT NULL,
      status VARCHAR(50) NOT NULL,
      priority INT DEFAULT 0,
      version INT DEFAULT 1,
      last_status_changed_at TIMESTAMP NULL DEFAULT NULL,
      accepted_at TIMESTAMP NULL DEFAULT NULL,
      printing_started_at TIMESTAMP NULL DEFAULT NULL,
      ready_at TIMESTAMP NULL DEFAULT NULL,
      cancelled_at TIMESTAMP NULL DEFAULT NULL,
      completed_at TIMESTAMP NULL DEFAULT NULL,
      cancellation_reason_code VARCHAR(50) NULL DEFAULT NULL,
      cancellation_description VARCHAR(255) NULL DEFAULT NULL,
      estimated_completion_at TIMESTAMP NULL DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id),
      INDEX idx_print_jobs_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS print_job_history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      print_job_id INT NOT NULL,
      previous_status VARCHAR(50) NOT NULL,
      new_status VARCHAR(50) NOT NULL,
      actor_type VARCHAR(20) NOT NULL,
      transition_name VARCHAR(50) NOT NULL,
      changed_by_user_id INT NOT NULL,
      reason_code VARCHAR(50) NULL DEFAULT NULL,
      reason_description VARCHAR(255) NULL DEFAULT NULL,
      correlation_id VARCHAR(36) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (print_job_id) REFERENCES print_jobs(id),
      FOREIGN KEY (changed_by_user_id) REFERENCES users(id),
      INDEX idx_print_job_history_job_id (print_job_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS outbox_events (
      id INT AUTO_INCREMENT PRIMARY KEY,
      event_id VARCHAR(36) NOT NULL UNIQUE,
      event_type VARCHAR(100) NOT NULL,
      aggregate_type VARCHAR(100) NOT NULL,
      aggregate_id VARCHAR(100) NOT NULL,
      payload LONGTEXT NOT NULL,
      status VARCHAR(50) NOT NULL,
      retry_count INT DEFAULT 0,
      error_log TEXT DEFAULT NULL,
      correlation_id VARCHAR(100) NOT NULL,
      event_version INT NOT NULL DEFAULT 1,
      occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      worker_id VARCHAR(100) DEFAULT NULL,
      processing_started_at TIMESTAMP NULL DEFAULT NULL,
      processed_at TIMESTAMP NULL DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_outbox_events_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS fulfillments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_id INT NOT NULL UNIQUE,
      print_job_id INT NOT NULL UNIQUE,
      shop_id INT NOT NULL,
      student_id INT NOT NULL,
      status VARCHAR(50) NOT NULL,
      mode VARCHAR(50) NOT NULL,
      assigned_agent_id INT DEFAULT NULL,
      otp_hash VARCHAR(255) DEFAULT NULL,
      otp_expires_at TIMESTAMP NULL DEFAULT NULL,
      otp_attempts INT DEFAULT 0,
      delivery_attempts INT DEFAULT 0,
      proof_of_delivery_reference VARCHAR(255) DEFAULT NULL,
      failure_reason VARCHAR(255) DEFAULT NULL,
      estimated_delivery_at TIMESTAMP NULL DEFAULT NULL,
      actual_delivery_at TIMESTAMP NULL DEFAULT NULL,
      otp_verified_at TIMESTAMP NULL DEFAULT NULL,
      version INT DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (print_job_id) REFERENCES print_jobs(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id),
      FOREIGN KEY (assigned_agent_id) REFERENCES users(id),
      INDEX idx_fulfillments_status (status),
      INDEX idx_fulfillments_order_id (order_id),
      INDEX idx_fulfillments_print_job_id (print_job_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS fulfillment_history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      fulfillment_id INT NOT NULL,
      previous_status VARCHAR(50) NOT NULL,
      new_status VARCHAR(50) NOT NULL,
      transition_name VARCHAR(50) NOT NULL,
      performed_by_type VARCHAR(50) NOT NULL,
      performed_by_user_id INT NOT NULL,
      failure_reason VARCHAR(255) DEFAULT NULL,
      proof_of_delivery_reference VARCHAR(255) DEFAULT NULL,
      metadata JSON DEFAULT NULL,
      correlation_id VARCHAR(100) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (fulfillment_id) REFERENCES fulfillments(id),
      FOREIGN KEY (performed_by_user_id) REFERENCES users(id),
      INDEX idx_fulfillment_history_fulfillment_id (fulfillment_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS delivery_agent_availability (
      agent_id INT PRIMARY KEY,
      status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
      active_workload INT DEFAULT 0,
      last_assigned_at TIMESTAMP NULL DEFAULT NULL,
      last_idle_at TIMESTAMP NULL DEFAULT NULL,
      version INT DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (agent_id) REFERENCES users(id),
      INDEX idx_delivery_agent_availability_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS delivery_assignments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      fulfillment_id INT NOT NULL,
      order_id INT NOT NULL,
      shop_id INT NOT NULL,
      student_id INT NOT NULL,
      agent_id INT NOT NULL,
      status VARCHAR(50) NOT NULL,
      correlation_id VARCHAR(100) NOT NULL,
      version INT DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (fulfillment_id) REFERENCES fulfillments(id),
      FOREIGN KEY (order_id) REFERENCES orders(id),
      FOREIGN KEY (shop_id) REFERENCES shops(id),
      FOREIGN KEY (student_id) REFERENCES users(id),
      FOREIGN KEY (agent_id) REFERENCES users(id),
      INDEX idx_delivery_assignments_status (status),
      INDEX idx_delivery_assignments_fulfillment_id (fulfillment_id),
      INDEX idx_delivery_assignments_agent_id (agent_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS delivery_history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      delivery_assignment_id INT NOT NULL,
      previous_status VARCHAR(50) NOT NULL,
      new_status VARCHAR(50) NOT NULL,
      transition_name VARCHAR(50) NOT NULL,
      performed_by_user_id INT NOT NULL,
      performed_by_type VARCHAR(50) NOT NULL,
      metadata JSON DEFAULT NULL,
      correlation_id VARCHAR(100) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (delivery_assignment_id) REFERENCES delivery_assignments(id),
      FOREIGN KEY (performed_by_user_id) REFERENCES users(id),
      INDEX idx_delivery_history_assignment_id (delivery_assignment_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

    // ─── Phase 7: Order Tracking & Lifecycle Projection (MySQL) ────────────
    `CREATE TABLE IF NOT EXISTS processed_events (
      event_id VARCHAR(36) PRIMARY KEY,
      processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS order_lifecycle_projections (
      order_id INT PRIMARY KEY,
      order_hash VARCHAR(64) NOT NULL,
      student_id INT NOT NULL,
      shop_id INT NOT NULL,
      shop_name VARCHAR(255) NOT NULL,
      delivery_type ENUM('pickup', 'hostel') NOT NULL,
      hostel_address VARCHAR(300) DEFAULT NULL,
      total_price DECIMAL(12,2) NOT NULL,
      current_state VARCHAR(50) NOT NULL,
      payment_status VARCHAR(50) NOT NULL,
      invoice_number VARCHAR(100) DEFAULT NULL,
      print_job_id INT DEFAULT NULL,
      print_status VARCHAR(50) DEFAULT NULL,
      fulfillment_id INT DEFAULT NULL,
      fulfillment_status VARCHAR(50) DEFAULT NULL,
      assigned_agent_id INT DEFAULT NULL,
      agent_name VARCHAR(100) DEFAULT NULL,
      agent_phone VARCHAR(20) DEFAULT NULL,
      last_processed_version INT NOT NULL DEFAULT 0,
      last_processed_occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY uq_proj_order_hash (order_hash),
      INDEX idx_proj_student (student_id),
      INDEX idx_proj_shop (shop_id),
      INDEX idx_proj_agent (assigned_agent_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS order_lifecycle_timeline_events (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_id INT NOT NULL,
      event_id VARCHAR(36) NOT NULL,
      event_type VARCHAR(100) NOT NULL,
      state VARCHAR(50) NOT NULL,
      title VARCHAR(150) NOT NULL,
      description VARCHAR(500) NOT NULL,
      occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      actor_type ENUM('student', 'shop', 'agent', 'system') NOT NULL,
      actor_id INT DEFAULT NULL,
      metadata JSON DEFAULT NULL,
      correlation_id VARCHAR(36) NOT NULL,
      causation_id VARCHAR(36) NOT NULL,
      FOREIGN KEY (order_id) REFERENCES order_lifecycle_projections(order_id) ON DELETE CASCADE,
      UNIQUE KEY uq_order_event_id (order_id, event_id),
      INDEX idx_timeline_occurred (order_id, occurred_at),
      INDEX idx_timeline_event_id (event_id),
      INDEX idx_timeline_correlation (correlation_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS dead_letter_events (
      id INT AUTO_INCREMENT PRIMARY KEY,
      event_id VARCHAR(36) NOT NULL UNIQUE,
      aggregate_id VARCHAR(100) NOT NULL,
      aggregate_type VARCHAR(100) NOT NULL,
      event_type VARCHAR(100) NOT NULL,
      payload LONGTEXT NOT NULL,
      error_message TEXT NOT NULL,
      retry_count INT NOT NULL,
      failed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS scheduling_shops_capacity (
      shop_id INT PRIMARY KEY,
      max_parallel_orders INT NOT NULL DEFAULT 5,
      overload_wait_threshold_seconds INT NOT NULL DEFAULT 7200,
      is_accepting_orders TINYINT(1) NOT NULL DEFAULT 1,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS scheduling_printers (
      id INT AUTO_INCREMENT PRIMARY KEY,
      shop_id INT NOT NULL,
      name VARCHAR(255) NOT NULL,
      status VARCHAR(50) NOT NULL,
      pages_per_minute INT NOT NULL DEFAULT 20,
      duplex_supported TINYINT(1) NOT NULL DEFAULT 1,
      color_supported TINYINT(1) NOT NULL DEFAULT 1,
      supported_paper_sizes TEXT NOT NULL,
      maximum_paper_weight INT NOT NULL DEFAULT 80,
      printable_media TEXT NOT NULL,
      warmup_time_seconds INT NOT NULL DEFAULT 30,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (shop_id) REFERENCES scheduling_shops_capacity(shop_id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS scheduling_printer_maintenance (
      id INT AUTO_INCREMENT PRIMARY KEY,
      printer_id INT NOT NULL,
      start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      reason VARCHAR(500) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (printer_id) REFERENCES scheduling_printers(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS scheduling_print_queue (
      id INT AUTO_INCREMENT PRIMARY KEY,
      shop_id INT NOT NULL,
      order_id INT NOT NULL UNIQUE,
      printer_id INT DEFAULT NULL,
      queue_position INT NOT NULL DEFAULT 0,
      estimated_start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      estimated_completion_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      pages_count INT NOT NULL,
      duplex TINYINT(1) NOT NULL DEFAULT 0,
      color TINYINT(1) NOT NULL DEFAULT 0,
      status VARCHAR(50) NOT NULL,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (shop_id) REFERENCES scheduling_shops_capacity(shop_id) ON DELETE CASCADE,
      FOREIGN KEY (printer_id) REFERENCES scheduling_printers(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS scheduling_inventory (
      id INT AUTO_INCREMENT PRIMARY KEY,
      shop_id INT NOT NULL,
      type VARCHAR(50) NOT NULL,
      variant VARCHAR(50) NOT NULL,
      quantity DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      unit VARCHAR(20) NOT NULL,
      low_stock_threshold DECIMAL(10,2) NOT NULL DEFAULT 100.00,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY uq_shop_inventory_item (shop_id, type, variant),
      FOREIGN KEY (shop_id) REFERENCES scheduling_shops_capacity(shop_id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS scheduling_processed_events (
      event_id VARCHAR(36) PRIMARY KEY,
      processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS scheduling_snapshots (
      shop_id INT PRIMARY KEY,
      last_event_id VARCHAR(36) NOT NULL,
      last_event_sequence INT NOT NULL,
      state_data LONGTEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS notifications (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      type VARCHAR(50) NOT NULL,
      priority VARCHAR(20) NOT NULL,
      title VARCHAR(255) NOT NULL,
      content TEXT NOT NULL,
      is_read TINYINT(1) NOT NULL DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS notification_templates (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE,
      subject VARCHAR(255) DEFAULT NULL,
      body_markdown TEXT NOT NULL,
      body_html TEXT NOT NULL,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS notification_preferences (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL UNIQUE,
      email_enabled TINYINT(1) NOT NULL DEFAULT 1,
      in_app_enabled TINYINT(1) NOT NULL DEFAULT 1,
      quiet_hours_start VARCHAR(5) DEFAULT NULL,
      quiet_hours_end VARCHAR(5) DEFAULT NULL,
      min_priority VARCHAR(20) DEFAULT 'low',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS notification_delivery_attempts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      notification_id INT NOT NULL,
      channel VARCHAR(50) NOT NULL,
      status VARCHAR(50) NOT NULL,
      error_message TEXT DEFAULT NULL,
      attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS notification_batches (
      id INT AUTO_INCREMENT PRIMARY KEY,
      shop_id INT NOT NULL,
      recipient_count INT NOT NULL,
      status VARCHAR(50) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS processed_notification_events (
      event_id VARCHAR(36) PRIMARY KEY,
      processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS analytics_daily_metrics (
      id INT AUTO_INCREMENT PRIMARY KEY,
      date DATE NOT NULL UNIQUE,
      total_orders INT NOT NULL DEFAULT 0,
      total_revenue DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      completed_orders INT NOT NULL DEFAULT 0,
      cancelled_orders INT NOT NULL DEFAULT 0,
      avg_completion_time_secs DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      avg_delivery_time_secs DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      low_stock_events INT NOT NULL DEFAULT 0,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS analytics_shop_metrics (
      id INT AUTO_INCREMENT PRIMARY KEY,
      shop_id INT NOT NULL UNIQUE,
      total_orders INT NOT NULL DEFAULT 0,
      completed_orders INT NOT NULL DEFAULT 0,
      cancelled_orders INT NOT NULL DEFAULT 0,
      total_revenue DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      avg_completion_time_secs DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      avg_delivery_time_secs DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      printer_utilization_pct DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
      queue_utilization_pct DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
      low_stock_events INT NOT NULL DEFAULT 0,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS analytics_user_metrics (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL UNIQUE,
      total_orders INT NOT NULL DEFAULT 0,
      completed_orders INT NOT NULL DEFAULT 0,
      cancelled_orders INT NOT NULL DEFAULT 0,
      total_spend DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      avg_order_value DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      last_order_at TIMESTAMP NULL DEFAULT NULL,
      version INT NOT NULL DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS analytics_order_facts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_id INT NOT NULL UNIQUE,
      shop_id INT NOT NULL,
      user_id INT NOT NULL,
      date DATE NOT NULL,
      revenue DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      page_count INT NOT NULL DEFAULT 0,
      is_color TINYINT(1) NOT NULL DEFAULT 0,
      order_created_at TIMESTAMP NOT NULL,
      payment_confirmed_at TIMESTAMP NULL DEFAULT NULL,
      print_started_at TIMESTAMP NULL DEFAULT NULL,
      print_completed_at TIMESTAMP NULL DEFAULT NULL,
      delivery_completed_at TIMESTAMP NULL DEFAULT NULL,
      cancelled_at TIMESTAMP NULL DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_order_facts_shop (shop_id),
      INDEX idx_order_facts_user (user_id),
      INDEX idx_order_facts_date (date)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS analytics_events_processed (
      event_id VARCHAR(36) PRIMARY KEY,
      processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    `CREATE TABLE IF NOT EXISTS analytics_snapshots (
      id INT AUTO_INCREMENT PRIMARY KEY,
      snapshot_date DATE NOT NULL UNIQUE,
      total_orders INT NOT NULL DEFAULT 0,
      total_revenue DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      total_completed INT NOT NULL DEFAULT 0,
      total_cancelled INT NOT NULL DEFAULT 0,
      last_event_sequence INT NOT NULL DEFAULT 0,
      state_data LONGTEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`
  ];

  const queries = isSQLite ? sqliteQueries : mysqlQueries;

  for (const q of queries) {
    try {
      await db.execute(q);
      const tableName = q.match(/CREATE TABLE IF NOT EXISTS (\w+)/)?.[1];
      if (tableName) {
        console.log(`  ✅ Table "${tableName}" ready`);
      } else {
        console.log(`  ✅ Database setup statement complete`);
      }
    } catch (err) {
      console.error('  ❌ Migration error:', err.message);
    }
  }

  // Ensure new columns exist for existing databases
  const alterQueries = [
    `ALTER TABLE users ADD COLUMN phone TEXT DEFAULT NULL`,
    `ALTER TABLE users ADD COLUMN hostel TEXT DEFAULT NULL`,
    `ALTER TABLE users ADD COLUMN room_number TEXT DEFAULT NULL`,
    `ALTER TABLE users ADD COLUMN wallet_balance REAL DEFAULT 0.00`,
    `ALTER TABLE orders ADD COLUMN payment_reference TEXT DEFAULT NULL`,
    `ALTER TABLE orders ADD COLUMN payment_uuid TEXT DEFAULT NULL`,
    `ALTER TABLE orders ADD COLUMN gateway_payment_id TEXT DEFAULT NULL`,
    `ALTER TABLE orders ADD COLUMN paid_at TEXT DEFAULT NULL`,
    `ALTER TABLE print_jobs ADD COLUMN version INT DEFAULT 1`,
    `ALTER TABLE print_jobs ADD COLUMN last_status_changed_at TEXT DEFAULT NULL`,
    `ALTER TABLE print_jobs ADD COLUMN accepted_at TEXT DEFAULT NULL`,
    `ALTER TABLE print_jobs ADD COLUMN printing_started_at TEXT DEFAULT NULL`,
    `ALTER TABLE print_jobs ADD COLUMN ready_at TEXT DEFAULT NULL`,
    `ALTER TABLE print_jobs ADD COLUMN cancelled_at TEXT DEFAULT NULL`,
    `ALTER TABLE print_jobs ADD COLUMN cancellation_reason_code TEXT DEFAULT NULL`,
    `ALTER TABLE print_jobs ADD COLUMN cancellation_description TEXT DEFAULT NULL`,
    `ALTER TABLE orders ADD COLUMN order_id VARCHAR(255) DEFAULT NULL`,
    `ALTER TABLE orders ADD COLUMN payment_status VARCHAR(50) DEFAULT 'UNPAID'`,
    `ALTER TABLE notifications MODIFY COLUMN type VARCHAR(50) NOT NULL DEFAULT 'system'`
  ];
  for (const q of alterQueries) {
    try { await db.execute(q); } catch (e) { } // Ignore if column already exists or command unsupported
  }

  // Seed super admin
  try {
    const hash = await bcrypt.hash(process.env.ADMIN_PASSWORD, 12);
    const [existing] = await db.execute('SELECT id FROM users WHERE email = ?', [process.env.ADMIN_EMAIL]);

    if (!existing || existing.length === 0) {
      await db.execute(
        'INSERT INTO users (name, email, password, role, is_verified) VALUES (?, ?, ?, ?, ?)',
        ['Super Admin', process.env.ADMIN_EMAIL, hash, 'admin', 1]
      );
      console.log('\n  👑 Super Admin created:', process.env.ADMIN_EMAIL);
    } else {
      // Update existing admin to ensure password and role are correct
      await db.execute(
        'UPDATE users SET password = ?, role = ?, is_verified = 1 WHERE email = ?',
        [hash, 'admin', process.env.ADMIN_EMAIL]
      );
      console.log('\n  👑 Super Admin updated:', process.env.ADMIN_EMAIL);
    }
  } catch (err) {
    console.error('  ❌ Admin seed error:', err.message);
  }

  console.log('\n✅ All migrations complete!\n');
  if (require.main === module) {
    process.exit(0);
  }
};

module.exports = migrate;

if (require.main === module) {
  migrate();
}
