export enum DeliveryTransition {
  ASSIGN = 'ASSIGN',
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT',
  START_PICKUP = 'START_PICKUP',
  COMPLETE_PICKUP = 'COMPLETE_PICKUP',
  COMPLETE_DELIVERY = 'COMPLETE_DELIVERY',
  FAIL_DELIVERY = 'FAIL_DELIVERY',
  RESTORE_AVAILABILITY = 'RESTORE_AVAILABILITY'
}
