export enum AnalyticsEventType {
  ORDER_CREATED = 'ORDER_CREATED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PRINT_STARTED = 'PRINT_STARTED',
  PRINT_COMPLETED = 'PRINT_COMPLETED',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  LOW_STOCK = 'LOW_STOCK'
}
