export enum FulfillmentStatus {
  READY = 'READY',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  PICKUP_COMPLETED = 'PICKUP_COMPLETED',
  FAILED = 'FAILED'
}
